// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwtBo97aiQ81U8vxjTmkKOk76kb9Fe41A',
    appId: '1:445212196583:web:c02a57dc41960bafbcec42',
    messagingSenderId: '445212196583',
    projectId: 'kothai-32a62',
    authDomain: 'kothai-32a62.firebaseapp.com',
    storageBucket: 'kothai-32a62.firebasestorage.app',
    measurementId: 'G-CP9G045CRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSrbkdZ-j6vVYv-yHw_SB695EdUmBT99E',
    appId: '1:445212196583:android:1e16c22327450336bcec42',
    messagingSenderId: '445212196583',
    projectId: 'kothai-32a62',
    storageBucket: 'kothai-32a62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKT5prqLPaLkeBvmpumtOZ-jUqbOHJyG8',
    appId: '1:445212196583:ios:cb0d96d3be8d6e40bcec42',
    messagingSenderId: '445212196583',
    projectId: 'kothai-32a62',
    storageBucket: 'kothai-32a62.firebasestorage.app',
    iosClientId: '445212196583-qrt93palvob5tgdtg3ftt2uf8le6l1ng.apps.googleusercontent.com',
    iosBundleId: 'com.example.kothaiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKT5prqLPaLkeBvmpumtOZ-jUqbOHJyG8',
    appId: '1:445212196583:ios:cb0d96d3be8d6e40bcec42',
    messagingSenderId: '445212196583',
    projectId: 'kothai-32a62',
    storageBucket: 'kothai-32a62.firebasestorage.app',
    iosBundleId: 'com.example.kothaiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwtBo97aiQ81U8vxjTmkKOk76kb9Fe41A',
    appId: '1:445212196583:web:846bf8cf5b8a0954bcec42',
    messagingSenderId: '445212196583',
    projectId: 'kothai-32a62',
    authDomain: 'kothai-32a62.firebaseapp.com',
    storageBucket: 'kothai-32a62.firebasestorage.app',
    measurementId: 'G-3DR3YVVSN3',
  );
}